//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [MetadataType(typeof(t儲值點數MD))]
    public partial class t儲值點數
    {
        public class t儲值點數MD
        {
            [Key]
            [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
            public int fDID { get; set; }

            public int fUID { get; set; }

            [Display(Name = "點數")]
            [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
            public int f點數 { get; set; }

            [Display(Name = "建立時間")]
            [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
            public System.DateTime f建立時間 { get; set; }
        }
    }
}
