//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [MetadataType(typeof(t私廚可預訂時間MD))]
    public partial class t私廚可預訂時間
    {
        public class t私廚可預訂時間MD
        {
            [Key]
            [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
            public int fTID { get; set; }

            [Display(Name = "[私廚][fCID]")]
            public int fCID { get; set; }

            [Display(Name = "日期")]
            public System.DateTime f日期 { get; set; }

            [Range(1, 2)]
            public int f時段 { get; set; }

            [Range(1, 2)]
            public int f狀態 { get; set; }
        }
    }
}
