//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [MetadataType(typeof(t私廚MD))]
    public partial class t私廚
    {
        public class t私廚MD
        {
            [Key]
            [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
            public int fCID { get; set; }

            [Display(Name = "[會員][fUID]")]
            public int fUID { get; set; }

            [Display(Name = "服務地區")]
            [Required(ErrorMessage = "您必須輸入服務地區！")]
            public string f服務地區 { get; set; }

            [Display(Name = "私廚簡介")]
            public string f私廚簡介 { get; set; }

        }
    }
}
