//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [MetadataType(typeof(t訂單MD))]
    public partial class t訂單
    {
        public class t訂單MD
        {

            [Key]
            [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
            public int fOID { get; set; }

            public int fUID { get; set; }

            public int fPID { get; set; }

            [Display(Name = "訂購日期")]
            [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Computed)]
            public System.DateTime f訂購日期 { get; set; }

            [Display(Name = "預定日期")]
            public string f預定日期 { get; set; }

            [Display(Name = "完成日期")]
            [DefaultValue("")]
            public string f評價日期 { get; set; }

            [Display(Name = "數量")]
            public int f數量 { get; set; }

            [Range(1,3)]
            [Display(Name = "狀態")]
            public int f狀態 { get; set; }

            [Display(Name = "評級")]
            public int f評級 { get; set; }

            [Display(Name = "評價內容")]
            public string f評價內容 { get; set; }
        }
        
    }
}
