//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t我的最愛> t我的最愛 { get; set; }
        public virtual DbSet<t私廚> t私廚 { get; set; }
        public virtual DbSet<t服務種類> t服務種類 { get; set; }
        public virtual DbSet<t訂單> t訂單 { get; set; }
        public virtual DbSet<t風格> t風格 { get; set; }
        public virtual DbSet<t販售項目> t販售項目 { get; set; }
        public virtual DbSet<t菜品> t菜品 { get; set; }
        public virtual DbSet<t會員> t會員 { get; set; }
        public virtual DbSet<t儲值點數> t儲值點數 { get; set; }
        public virtual DbSet<t私廚可預訂時間> t私廚可預訂時間 { get; set; }
    }
}
