//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class t我的最愛
    {
        public int fFID { get; set; }
        public int fUID { get; set; }
        public int fPID { get; set; }
    
        public virtual t販售項目 t販售項目 { get; set; }
        public virtual t會員 t會員 { get; set; }
    }
}
