//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class t會員
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t會員()
        {
            this.t我的最愛 = new HashSet<t我的最愛>();
            this.t私廚 = new HashSet<t私廚>();
            this.t儲值點數 = new HashSet<t儲值點數>();
            this.t訂單 = new HashSet<t訂單>();
        }
    
        public int fUID { get; set; }
        public string f帳號 { get; set; }
        public string f密碼 { get; set; }
        public string f電子郵件 { get; set; }
        public string f姓名 { get; set; }
        public string f暱稱 { get; set; }
        public string f電話 { get; set; }
        public string f生日 { get; set; }
        public string f詳細地址 { get; set; }
        public string f居住縣市 { get; set; }
        public string f會員照片 { get; set; }
        public Nullable<int> f點數 { get; set; }
        public Nullable<int> f權限 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t我的最愛> t我的最愛 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t私廚> t私廚 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t儲值點數> t儲值點數 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂單> t訂單 { get; set; }
    }
}
