//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class t私廚可預訂時間
    {
        public int fTID { get; set; }
        public int fCID { get; set; }
        public System.DateTime f日期 { get; set; }
        public int f時段 { get; set; }
        public int f狀態 { get; set; }
    
        public virtual t私廚 t私廚 { get; set; }
    }
}
