//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class t販售項目
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t販售項目()
        {
            this.t我的最愛 = new HashSet<t我的最愛>();
            this.t訂單 = new HashSet<t訂單>();
            this.t菜品 = new HashSet<t菜品>();
        }
    
        public int fPID { get; set; }
        public int fCID { get; set; }
        public int fSID { get; set; }
        public int fKID { get; set; }
        public string f項目名稱 { get; set; }
        public string f項目內容 { get; set; }
        public int f價格 { get; set; }
        public string f項目照片 { get; set; }
        public int f項目評級_ { get; set; }
        public bool f上架 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t我的最愛> t我的最愛 { get; set; }
        public virtual t私廚 t私廚 { get; set; }
        public virtual t服務種類 t服務種類 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂單> t訂單 { get; set; }
        public virtual t風格 t風格 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t菜品> t菜品 { get; set; }
    }
}
